dubbo:
  application:
    name:  springboot-task
  registry:
    address: localhost:2181
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8063

